// Generate the GitHub Pages site (docs/index.html) from the structured data in
// data/games/*.yaml. Like the README table, the site renders from the data —
// it is never hand-edited. A single self-contained HTML file: inline CSS, a few
// lines of dependency-free JS for client-side sort/filter.
//
//   npm run build:site
//
// GitHub Pages serves this from the /docs folder on the default branch.

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { parse } from 'yaml'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const GAMES_DIR = join(ROOT, 'data', 'games')
const OUT_DIR = join(ROOT, 'docs')

interface Source { title: string; url: string; primary?: boolean }
interface Game {
  id: string; name: string; family: string
  result: 'first-player-win' | 'second-player-win' | 'draw'
  strength: 'ultra-weak' | 'weak' | 'strong'
  approximate?: boolean
  board?: string; year: number | null; solved_by: string; verified: boolean
  sources: Source[]
}

const RESULT_PHRASE: Record<Game['result'], string> = {
  'first-player-win': 'First player wins',
  'second-player-win': 'Second player wins',
  draw: 'Draw',
}
const REPO = 'https://github.com/brianhliou/awesome-game-solving'

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

function loadGames(): Game[] {
  return readdirSync(GAMES_DIR)
    .filter((f) => f.endsWith('.yaml'))
    .map((f) => parse(readFileSync(join(GAMES_DIR, f), 'utf8')) as Game)
}

const PARTICLES = new Set(['van', 'von', 'der', 'den', 'de', 'da', 'di', 'du', 'la', 'le', 'ten'])
function cite(g: Game): { label: string; url: string } {
  const authors = g.solved_by.split(/[(;]/)[0]
  const head = authors.split(/,|&| and /)[0].trim()
  const tokens = head.split(/\s+/)
  let i = tokens.length - 1
  while (i > 0 && PARTICLES.has(tokens[i - 1].toLowerCase())) i--
  const surname = tokens.slice(i).join(' ').replace(/\.$/, '')
  const folklore = /folklore|classical hand analysis/i.test(head)
  const multi = /&| and |,|et al/i.test(authors)
  const label = folklore ? 'folklore' : `${surname}${multi ? ' et al.' : ''}${g.year ? ` ${g.year}` : ''}`
  const url = (g.sources.find((s) => s.primary) ?? g.sources[0])?.url ?? REPO
  return { label, url }
}

function rowHtml(g: Game): string {
  const result = RESULT_PHRASE[g.result] + (g.approximate ? ' <span class="eps">(ε-Nash)</span>' : '')
  const strengthLabel = g.strength + (g.approximate ? ' (approx.)' : '')
  const { label, url } = cite(g)
  const search = `${g.name} ${g.family} ${g.solved_by}`.toLowerCase()
  return `        <tr data-family="${esc(g.family)}" data-strength="${g.strength}" data-search="${esc(search)}">
          <td class="game">${esc(g.name)}${g.board ? `<span class="board">${esc(g.board)}</span>` : ''}</td>
          <td>${result}</td>
          <td><span class="badge s-${g.strength}">${esc(strengthLabel)}</span></td>
          <td class="num">${g.year ?? '—'}</td>
          <td><span class="fam">${esc(g.family)}</span></td>
          <td><a href="${esc(url)}" rel="noopener">${esc(label)}</a></td>
        </tr>`
}

function page(games: Game[]): string {
  const verified = games
    .filter((g) => g.verified)
    .sort((a, b) => (a.year ?? 0) - (b.year ?? 0) || a.name.localeCompare(b.name))
  const families = [...new Set(verified.map((g) => g.family))].sort()
  const famOptions = families.map((f) => `<option value="${esc(f)}">${esc(f)}</option>`).join('')
  const rows = verified.map(rowHtml).join('\n')
  const counts = {
    total: verified.length,
    strong: verified.filter((g) => g.strength === 'strong').length,
    families: families.length,
  }

  return `<!doctype html>
<!-- GENERATED by scripts/build-site.ts from data/games/*.yaml — do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Awesome Game Solving — the registry of solved games</title>
<meta name="description" content="A structured, citation-gated record of solved games: the result under perfect play, the method, and where to verify it.">
<style>
  :root { --bg:#0d1117; --fg:#e6edf3; --muted:#8b949e; --line:#21262d; --card:#161b22; --link:#58a6ff;
          --strong:#2ea043; --weak:#d29922; --ultra:#6e7681; }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--fg); font:16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; }
  a { color:var(--link); text-decoration:none; } a:hover { text-decoration:underline; }
  .wrap { max-width:1000px; margin:0 auto; padding:2.5rem 1.25rem 4rem; }
  header h1 { font-size:2rem; margin:0 0 .35rem; }
  .tagline { color:var(--muted); font-size:1.1rem; margin:0 0 1rem; max-width:60ch; }
  .meta { color:var(--muted); font-size:.9rem; margin:0 0 2rem; }
  .meta a { color:var(--link); }
  .defs { background:var(--card); border:1px solid var(--line); border-radius:10px; padding:1rem 1.25rem; margin:0 0 2rem; }
  .defs h2 { font-size:1rem; margin:0 0 .5rem; }
  .defs ul { margin:0; padding-left:1.1rem; } .defs li { margin:.25rem 0; color:var(--muted); }
  .defs b { color:var(--fg); }
  .controls { display:flex; flex-wrap:wrap; gap:.6rem; margin:0 0 1rem; }
  .controls input, .controls select { background:var(--card); color:var(--fg); border:1px solid var(--line);
          border-radius:8px; padding:.5rem .7rem; font-size:.95rem; }
  .controls input { flex:1; min-width:200px; }
  table { width:100%; border-collapse:collapse; font-size:.93rem; }
  th, td { text-align:left; padding:.55rem .6rem; border-bottom:1px solid var(--line); vertical-align:top; }
  th { color:var(--muted); font-weight:600; cursor:pointer; user-select:none; white-space:nowrap; }
  th:hover { color:var(--fg); }
  td.num { font-variant-numeric:tabular-nums; }
  .game { font-weight:600; } .board { display:block; color:var(--muted); font-weight:400; font-size:.8rem; }
  .badge { padding:.1rem .5rem; border-radius:999px; font-size:.78rem; white-space:nowrap; color:#fff; }
  .s-strong { background:var(--strong); } .s-weak { background:var(--weak); color:#1a1a1a; } .s-ultra-weak { background:var(--ultra); }
  .fam { color:var(--muted); font-size:.85rem; }
  .eps { color:var(--muted); font-size:.85em; }
  .empty { color:var(--muted); padding:1rem .6rem; display:none; }
  footer { margin-top:2.5rem; color:var(--muted); font-size:.85rem; border-top:1px solid var(--line); padding-top:1.25rem; }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>Awesome Game Solving</h1>
    <p class="tagline">The canonical reference for solved games: every known result, the method that produced it, and the code to verify it.</p>
    <p class="meta">${counts.total} solved games · ${counts.strong} strongly solved · ${counts.families} families · citation-gated · <a href="${REPO}" rel="noopener">source &amp; contribute on GitHub →</a></p>
  </header>

  <section class="defs">
    <h2>What "solved" means</h2>
    <ul>
      <li><b>Ultra-weak</b> — the value of the starting position is known (who wins, or draw), but not how.</li>
      <li><b>Weak</b> — the value <em>and</em> a strategy to achieve it from the start are known.</li>
      <li><b>Strong</b> — the value is known for every reachable position, not just the start (a full tablebase).</li>
    </ul>
  </section>

  <div class="controls">
    <input id="q" type="search" placeholder="Search games, solvers, families…" aria-label="Search">
    <select id="family" aria-label="Filter by family"><option value="">All families</option>${famOptions}</select>
    <select id="strength" aria-label="Filter by strength">
      <option value="">All strengths</option><option value="strong">Strong</option><option value="weak">Weak</option><option value="ultra-weak">Ultra-weak</option>
    </select>
  </div>

  <table id="registry">
    <thead><tr>
      <th data-sort="game">Game</th><th data-sort="result">Result</th><th data-sort="strength">Strength</th>
      <th data-sort="year" class="num">Year</th><th data-sort="family">Family</th><th>Source</th>
    </tr></thead>
    <tbody>
${rows}
    </tbody>
  </table>
  <div class="empty" id="empty">No games match.</div>

  <footer>
    Generated from structured data — the dataset is the product. The README table and this page render from <code>data/games/*.yaml</code>.
    Unsolved games live on the <a href="${REPO}#frontier" rel="noopener">frontier</a>, never as catalog entries. Released under CC0.
  </footer>
</div>

<script>
  const rows = [...document.querySelectorAll('#registry tbody tr')];
  const q = document.getElementById('q'), fam = document.getElementById('family'),
        str = document.getElementById('strength'), empty = document.getElementById('empty');
  function apply() {
    const term = q.value.trim().toLowerCase(), f = fam.value, s = str.value;
    let shown = 0;
    for (const r of rows) {
      const ok = (!term || r.dataset.search.includes(term)) &&
                 (!f || r.dataset.family === f) && (!s || r.dataset.strength === s);
      r.style.display = ok ? '' : 'none'; if (ok) shown++;
    }
    empty.style.display = shown ? 'none' : 'block';
  }
  [q, fam, str].forEach((el) => el.addEventListener('input', apply));

  const tbody = document.querySelector('#registry tbody');
  const dir = {};
  document.querySelectorAll('th[data-sort]').forEach((th, idx) => th.addEventListener('click', () => {
    const key = th.dataset.sort; dir[key] = !dir[key]; const mul = dir[key] ? 1 : -1;
    rows.sort((a, b) => {
      let av = a.children[idx].textContent.trim(), bv = b.children[idx].textContent.trim();
      if (key === 'year') { return ((+av || 0) - (+bv || 0)) * mul; }
      return av.localeCompare(bv) * mul;
    });
    rows.forEach((r) => tbody.appendChild(r));
  }));
</script>
</body>
</html>
`
}

mkdirSync(OUT_DIR, { recursive: true })
const games = loadGames()
writeFileSync(join(OUT_DIR, 'index.html'), page(games))
const n = games.filter((g) => g.verified).length
console.log(`Generated docs/index.html: ${n} verified of ${games.length} records.`)
